FROM continuumio/miniconda3
MAINTAINER Felipe Marques de Almeida <almeidafmarques@gmail.com>
SHELL ["/bin/bash", "-c"]
WORKDIR /work

# update conda
RUN conda update -n base -c defaults conda

# install procps
RUN apt-get update && \
		apt-get install -y procps

###################### RENV IMAGE #################################

# Get scripts
ADD scripts/rscripts /work/rscripts
ADD scripts/bscripts /work/bscripts

# Set main R dependencies
## Add R repo key
RUN apt-get update && \
			DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common gnupg build-essential && \
			apt-get update && \
			rm -rf /var/lib/apt/lists/* && \
			apt-get clean  && \
			apt-get update && \
			apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && \
			add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'

## Install R
RUN DEBIAN_FRONTEND=noninteractive apt update && \
			DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
			add-apt-repository ppa:marutter/c2d4u3.5 && \
			DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y r-api-3.5 r-base r-base-core

## Install R-packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
			DEBIAN_FRONTEND=noninteractive apt-get --option Acquire::Retries=100 --option Acquire::http::Timeout="300" install -yq r-cran-optparse r-cran-rmysql r-bioc-gviz r-cran-xml pandoc
RUN DEBIAN_FRONTEND=noninteractive apt-get --option Acquire::Retries=100 --option Acquire::http::Timeout="300" install -yq r-cran-plyr libssl-dev libcurl4-openssl-dev libxml2-dev libudunits2-dev libcairo2-dev libpq-dev r-cran-rmarkdown
RUN DEBIAN_FRONTEND=noninteractive Rscript /work/rscripts/installPack.R && \
			apt-get clean

# METADATA and REPORTS
# Add local files
ADD reports /work/reports
RUN rm /work/reports/aro_index.tsv /work/reports/victors_metadata.tsv

# Download Victors metadata
RUN apt-get install -y wget && \
			cd /work/reports && \
			wget "http://www.phidias.us/victors/export_text.php?c_mc_pathogen_id=&c_phi_function=Virulence%20factor&c_mc_victor_name=&c_gene_locus_tag=&db_type=gene_gi&db_id=&c_max_tmhmm_PredHel=1&c_max_tmhmm_PredHel_check=&c_min_spaan_score_check=&c_min_spaan_score=0.51&keywords=&c_human_alignment=&c_mouse_alignment=&c_localization[]=Any&cog_cat_id[]=" -O /work/reports/victors_metadata.tsv

# Download CARD metadata
RUN cd /work/reports && \
			wget -O card-data.tar.bz2 https://card.mcmaster.ca/download/0/broadstreet-v3.1.0.tar.bz2 && \
			tar jxvf card-data.tar.bz2 && \
			rm card-data.tar.bz2

# Make Rmds executable
RUN chmod a+rx /work/reports/*.Rmd

# Make rscripts executable
RUN chmod a+rx /work/rscripts/*

# Make bscripts executable
RUN chmod a+rx /work/bscripts/*

# Set PATH
ENV PATH="$PATH:/work/rscripts"

# Re-set workidir
WORKDIR /work
RUN chmod -R a+rw /work

###################### pipeline tools installation #############################

###############################
### tools that rely on PERL ###
###############################
RUN conda create -n PERL_env -c bioconda -c conda-forge -c defaults -y "prokka>=1.14" mlst nomkl islandpath

# Update prokka database with TIGRFAMs hmm
RUN wget https://ftp.ncbi.nlm.nih.gov/hmm/TIGRFAMs/release_15.0/TIGRFAMs_15.0_HMM.LIB.gz && \
		gzip -d TIGRFAMs_15.0_HMM.LIB.gz && \
		mv TIGRFAMs_15.0_HMM.LIB TIGRFAMs_15.hmm && \
		mv TIGRFAMs_15.hmm /opt/conda/envs/PERL_env/db/hmm/ && \
    conda run -n PERL_env prokka --setupdb

# fix islandpath-dimob pl script (and splitgenbank script biopython dependency)
RUN git clone https://github.com/brinkmanlab/islandpath.git ./islandpath && \
		ln -rs ./islandpath/Dimob.pl /usr/local/bin && \
		conda run -n PERL_env python -m pip install biopython

#####################################
### tools that rely on PYTHON 3.6 ###
#####################################
RUN conda create -y -c bioconda -c conda-forge -c defaults -n PY36_env "python>=3.6" "rgi>=5.2.0" refseq_masher nomkl && \
		conda clean -afy

#####################################
### tools that rely on ANY PYTHON ###
#####################################
RUN conda install -c bioconda -c conda-forge -c defaults -y samtools "platon>=1.6.0" "biopython>=1.71" \
		plasmidfinder phispy "blast>=2.11.0" "diamond>=2" prodigal hmmer minimap2 bedtools bc ncbi-amrfinderplus \
		emboss nomkl  && \
		conda clean -afy
RUN python3 -m pip install phigaro==2.3.0
RUN git clone https://github.com/fmalmeida/gff-toolbox.git && \
		cd gff-toolbox && \
		python3 -m pip install setuptools && \
		python3 setup.py install && \
		gff-toolbox -h

# Install resfinder
RUN conda install -c bioconda -c conda-forge -c defaults -y kma && \
		python3 -m pip install tabulate biopython cgecore gitpython setuptools python-dateutil
RUN git clone -b 4.0 https://git@bitbucket.org/genomicepidemiology/resfinder.git

###############################################################
### tool that require specific version of a specific module ###
###############################################################
RUN conda create -y -n digIS 'python=3.7' nomkl && \
		source activate digIS && \
		pip3 install biopython==1.73 numpy bcbio-gff && \
		conda deactivate && \
		conda clean -afy

###################
### other tools ###
###################
# Install NANOPOLISH
RUN apt-get update && apt-get install -y build-essential libhdf5-dev
RUN git clone --recursive https://github.com/jts/nanopolish.git \
		&& cd nanopolish \
		&& make all \
		&& rm /work/nanopolish/hdf5-1.8.14.tar.gz /work/nanopolish/eigen-3.3.7.tar.bz2
ENV PATH="$PATH:/work/nanopolish"

# Install digIS
RUN pip3 install biopython bcbio-gff numpy
RUN git clone https://github.com/janka2012/digIS.git
ENV PATH="$PATH:/work/digIS"

#########################
### my custom scripts ###
#########################
COPY scripts/bscripts /work/bscripts
RUN chmod a+rwx /work/bscripts/*

COPY scripts/pscripts/splitgenbank.py /usr/local/bin/splitgenbank.py
RUN chmod a+x /usr/local/bin/splitgenbank.py

COPY scripts/pscripts/resfinder2gff.py /usr/local/bin/resfinder2gff.py
RUN chmod a+x /usr/local/bin/resfinder2gff.py

COPY scripts/pscripts/run_blasts.py /usr/local/bin/run_blasts.py
RUN chmod a+x /usr/local/bin/run_blasts.py && \
			python3 -m pip install docopt pandas
