# Base image https://hub.docker.com/u/rocker/
FROM rocker/shiny:latest

# Owner
MAINTAINER Felipe Marques de Almeida <marques.felipe@aluno.unb.br>

# system libraries of general use
## install debian packages
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
    libxml2-dev \
    libcairo2-dev \
    libsqlite3-dev \
    libmariadbd-dev \
    libpq-dev \
    libssh2-1-dev \
    unixodbc-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    r-bioc-biostrings \
    r-bioc-iranges \
    ncbi-blast+

## update system libraries
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

# Set workdir
WORKDIR /app

# Install Java
RUN apt-get -y install default-jre r-cran-rjava

# Install renv & restore packages
RUN Rscript -e 'install.packages(c("bookdown", "rmarkdown", "shiny", "shinyFiles", "dplyr", "dbplyr", "RSQLite", "DT", "glue", "stringr", "DataCombine", "shinythemes", "stringr", "openxlsx"), dependencies=TRUE)'

# Install bedtools
RUN apt-get install -y bedtools

## Get scripts
COPY scripts/rscripts/shiny_parser.Rmd /app/shiny_parser.Rmd
COPY scripts/rscripts/shiny_parser_func.R /app/shiny_parser_func.R
COPY scripts/rscripts/get_attributes_field.R /app/get_attributes_field.R
COPY scripts/rscripts/blast_app.R /app/blast_app.R
COPY scripts/rscripts/SQL_parser.R /app/SQL_parser.R

# expose port
EXPOSE 3838

# run app on container start
CMD Rscript -e 'rmarkdown::run("shiny_parser.Rmd", shiny_args = list(launch.browser = T, host = "0.0.0.0", port = 3838))'
