FROM continuumio/miniconda3
LABEL MAINTAINER Felipe Marques de Almeida <marques.felipe@aluno.unb.br>
SHELL ["/bin/bash", "-c"]
WORKDIR /work

# Install antismash
RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge
RUN conda create -y -n antismash antismash

# Download databases
RUN source activate antismash && \
    download-antismash-databases

# install seqret
RUN conda install -y -n antismash -c bioconda -c conda-forge -c anaconda -c defaults emboss

# fix matplotlib
RUN mkdir /matplotlib && \
    chmod -R 777 /matplotlib
ENV MPLCONFIGDIR=/matplotlib
